name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Install, build, and upload your site
        uses: withastro/action@v2
        with:
          path: .  # Ajusta esto si tu proyecto Astro está en un subdirectorio
          node-version: 20
          package-manager: npm  # Cambia esto si usas otro administrador de paquetes

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: List generated files
        run: ls -la ./dist  # Ajusta esta ruta si es necesario

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
